"""added content in bank account table

Revision ID: 131cf8649c2c
Revises: 54b1740356ae
Create Date: 2024-11-29 15:04:37.757335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131cf8649c2c'
down_revision: Union[str, None] = '54b1740356ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
