"""added content in bank acc

Revision ID: 7b29ae2ccea2
Revises: b5684cf94448
Create Date: 2024-11-26 12:47:31.895234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b29ae2ccea2'
down_revision: Union[str, None] = 'b5684cf94448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_account', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_account', sa.Column('content', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
