"""transaction amount and transaction type column added in notification table

Revision ID: d582a82e986a
Revises: faf4f06cbcb7
Create Date: 2024-12-03 16:11:01.579571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd582a82e986a'
down_revision: Union[str, None] = 'faf4f06cbcb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('transaction_amount', sa.Float(), nullable=True))
    op.add_column('notifications', sa.Column('transaction_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'transaction_type')
    op.drop_column('notifications', 'transaction_amount')
    # ### end Alembic commands ###
